service: serverless-typescript
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: "us-east-1"

functions:
  helloWorld:
    handler: src/helloWorld.handler
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
