org: ninjasujan
app: layers-functions
service: lambda-layer
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: "us-east-1"
  stage: ${env:DEPLOY_STAGE}
  apiGateway:
    restApiId: aabdcyfq1f
    restApiRootResourceId: v3q8b97do8

package:
  individually: true

layers:
  dependecy:
    path: layer
    package:
      exclude:
        - src/**
      include:
        - layer/**
    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
      - nodejs12.x
      - nodejs14.x
    retain: false
    description: optional description for your layer
    tags:
      layer: testLayer

functions:
  uuid:
    handler: src/uuid.getuuid
    layers:
      - { Ref: DependecyLambdaLayer }
    package:
      exclude:
        - layer/**
        - src/nanoid.js
      include:
        - src/uuid.js
    events:
      - http:
          path: /uuid
          method: get
    environment:
      STAGE: ${env:STAGE}
    tags:
      function: testFunction

  nanoid:
    handler: src/nanoid.getNanoId
    layers:
      - { Ref: DependecyLambdaLayer }
    package:
      exclude:
        - layer/**
        - src/uuid.js
      include:
        - src/nanoid.js
    events:
      - http:
          path: /nanoid
          method: get
    environment:
      STAGE: ${env:STAGE}
    tags:
      function: testFunction

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
