org: ninjasujan
app: layers-functions
service: lambda-layer
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: "us-east-1"
  stage: ${env:STAGE}

package:
  individually: true

layers:
  dependecy:
    path: layer
    package:
      exclude:
        - src/**
      include:
        - layer/**
    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
      - nodejs12.x
      - nodejs14.x
    retain: false
    description: optional description for your layer
    tags:
      layer: testLayer

functions:
  hello:
    handler: src/handler.getuuid
    layers:
      - { Ref: DependecyLambdaLayer }
    package:
      exclude:
        - layer/**
      include:
        - src/**
    events:
      - http:
          path: /
          method: get
    environment:
      STAGE: ${env:STAGE}
    tags:
      function: testFunction

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
